---
title: "Evapotranspiration calculation"
subtitle: "EAS 520"
author: "Ronny Hernández Mora"
date: "2/27/2021"
always_allow_html: yes
output:
  rmdformats::downcute:
    code_folding: hide
    fig_width: 12
    fig_height: 8
    use_bookdown: true
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(dplyr)
library(lubridate)
library(janitor)
library(readr)
library(tidyr)
library(stringr)
library(ggplot2)
library(skimr)
library(feather)

# Import data

## Temperature
temperature_sensors <- read_csv("data/COSTA RICA - Santa Rosa National Park, Guanacaste 2013-06-06_2020-05-11_sensors.csv",
                    col_types = cols(`Air Temperature (34810)` = col_number(), 
                                     `Air Temperature (9861197)` = col_number(), 
                                     `Air Temperature (248)` = col_number(), 
                                     `Air Temperature (1)` = col_number(), 
                                     `Air Temperature (2)` = col_number())) %>% 
  clean_names() %>% 
  rename("temp_principe_wsn_pheno_34810" = "air_temperature_34810",
         "temp_perros_tower_hobo" = "air_temperature_9861197",
         "temp_phenology_tower_hobo" = "air_temperature_9861198",
         "temp_principe_wsn_pheno_248" = "air_temperature_248",
         "temp_carbon_tower_net_radiometer" = "air_temperature_1",
         "temp_principe_tower_campbell" = "air_temperature_2"
  ) %>% 
   pivot_longer(cols = c("temp_principe_wsn_pheno_34810",
                        "temp_perros_tower_hobo",
                        "temp_phenology_tower_hobo",
                        "temp_principe_wsn_pheno_248",
                        "temp_carbon_tower_net_radiometer",
                        "temp_principe_tower_campbell"
                        ),
               names_to = "dataset") %>% 
  filter(!is.na(value),
         value > 0) %>% 
  separate(time_stamp, into = c("date", "time"), sep = " ") %>% 
  mutate(time = str_sub(time, start = 1, end = 5)) %>% 
  unite(col = date_time, date, time, sep = " ") %>% 
  mutate(date_time = ymd_hm(date_time)) %>% 
  rename("temperature" = "value")


## Read carbon tower data with error removal
carbon_tower_eddy_error_removal <- read_csv("data/COSTARICA-SantaRosaNationalPark,Guanacaste_CarbonTower(New)_EddyCo._CampbellCR3000(1)_20130607_20190512_error_removal.csv") %>% 
  clean_names()

## Read principe tower data with error removal
principe_tower_eddy_error_removal <- read_csv("data/COSTARICA-SantaRosaNationalPark,Guanacaste_PrincipeTower(New)_EddyCo._CampbellCR3000(2)_20151213_20190622_error_removal.csv") %>% 
  clean_names()
```




```{r}

```





# Data aggregation

We are going to unite all the observations from both towers. There are months
were we have only observations from one tower, and there are other periods where
we have observations from both towers.

At first we need to get rid of second values in order to unite the two
data sets.

## Steps
```{r}
carbon_no_error <- carbon_tower_eddy_error_removal %>% 
    select(date_time, sensible_heat_flux, co2_flux, latent_heat_flux,
         mean_co2_concentration, mean_h2o_vapour_concentration, 
         mean_moist_air_density, mean_thermocouple_temp) %>% 
  mutate(tower = "carbon_tower")

principe_no_error <- principe_tower_eddy_error_removal %>% 
    select(date_time, sensible_heat_flux, co2_flux, latent_heat_flux,
         mean_co2_concentration, mean_h2o_vapour_concentration, 
         mean_moist_air_density, mean_thermocouple_temp) %>% 
  mutate(tower = "principe_tower")
         # air_temperature, humidity, saturation_vapour_pressure_k_pa)

eddy_complete_no_error <- rbind(carbon_no_error, principe_no_error) %>% 
  separate(date_time, into = c("date", "time"), sep = " ") %>% 
  mutate(time = str_sub(time, start = 1, end = 5)) %>% 
  unite(col = date_time, date, time, sep = " ") %>% 
  mutate(date_time = ymd_hm(date_time))

# Removemos observaciones duplicadas basados en date_time
check_remove_duplicates <- eddy_complete_no_error %>% 
  distinct(date_time, .keep_all = TRUE)
```

```{r}
# Unidades = kgH2O m−2 d−1

# Unir temperatura
eddy_temp <- check_remove_duplicates %>% 
  left_join(temperature_converted, by = "date_time") %>% 
  filter(!is.na(temperature))

le_eddy_temp <- eddy_temp %>% 
  mutate(evapotranspiration_kg = LE.to.ET(latent_heat_flux,
                                          temperature)) %>% 
  # Transform units
  mutate(evapotranspiration_mol = kg.to.mol((evapotranspiration_kg) * 1000))

le_grouped <- le_eddy_temp %>% 
  mutate(date = as.Date(date_time)) %>% 
  # mutate(check = ymd(date))
  group_by(ymd(date)) %>% 
  summarise(
    mean = mean(evapotranspiration_mol, na.rm = TRUE),
    total = sum(evapotranspiration_mol, na.rm = TRUE)
  ) %>% 
  rename("date" = `ymd(date)`)
```


```{r}
le_grouped %>% 
  mutate(date = ymd(date)) %>%
  # # filter values above 0.05
  # filter(evapotranspiration_mol < 1000 & evapotranspiration_mol > -500) %>%
  # # filter(year(date_time) == 2013) %>% 
  ggplot(aes(x = date, y = total)) +
  geom_point(alpha = 0.5) +
  # scale_x_datetime(date_labels = "%b", breaks = "months") +
  theme_light(base_size = 21) +
  theme(axis.text.x = element_text(angle = 75, h = 1)) +
  labs(title = "Total evapotranspiration",
       subtitle = "Al the datapoints available",
       x = "Date", y = "Evapotranspiration mmol m-2 s-1")

le_grouped %>% 
  mutate(date = ymd(date)) %>%
  # # filter values above 0.05
  # filter(evapotranspiration_mol < 1000 & evapotranspiration_mol > -500) %>%
  # # filter(year(date_time) == 2013) %>% 
  ggplot(aes(x = date, y = mean)) +
  geom_point(alpha = 0.5) +
  # scale_x_datetime(date_labels = "%b", breaks = "months") +
  theme_light(base_size = 21) +
  theme(axis.text.x = element_text(angle = 75, h = 1)) +
  labs(title = "Total evapotranspiration",
       subtitle = "Al the datapoints available",
       x = "Date", y = "Evapotranspiration mmol m-2 s-1")
```

## Check termocoupled temp with temperature

```{r}
eddy_temp %>% 
  drop_na() %>% 
  filter(temperature > 10) %>% 
  ggplot(aes(x = mean_thermocouple_temp, y = temperature)) +
  geom_point()

eddy_temp %>% 
  select(mean_thermocouple_temp, temperature) %>% 
  View()
```









